name: Build Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn
      - name: Run Test
        run: yarn test:ci
      - name: Run Build
        run: yarn build
