name: Publish

on: workflow_dispatch

env:
  outputDir: "./dist"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn
      - name: Run Test
        run: yarn test:ci
      - name: Run Build
        run: yarn build
      - name: "Publish"
        working-directory: ${{ env.outputDir }}
        run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
          yarn publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
